#!/bin/bash

## Script to set the key for mate terminal colors

palette="#1B1B1D1D1E1E:#F9F926267272:#8282B4B41414:#FDFD97971F1F:#5656C2C2D6D6:#8C8C5454FEFE:#464654545757:#CCCCCCCCC6C6:#505053535454:#FFFF59599595:#B6B6E3E35454:#FEFEEDED6C6C:#8C8CEDEDFFFF:#9E9E6F6FFEFE:#89899C9CA1A1:#F8F8F8F8F2F2"
bd_color="#FFFFFFFFFFFF"
fg_color="#A0A0A0A0A0A0"
bg_color="#1C1C1C1C1C1C"
app=set-terminal-color

chsh -s /usr/bin/fish

gsettings set org.mate.terminal.profile:/org/mate/terminal/profiles/default/ background-color $bg_color
gsettings set org.mate.terminal.profile:/org/mate/terminal/profiles/default/ foreground-color $fg_color
gsettings set org.mate.terminal.profile:/org/mate/terminal/profiles/default/ bold-color $bd_color
gsettings set org.mate.terminal.profile:/org/mate/terminal/profiles/default/ palette $palette
gsettings set org.mate.terminal.profile:/org/mate/terminal/profiles/default/ use-theme-colors false
gsettings set org.mate.terminal.profile:/org/mate/terminal/profiles/default/ bold-color-same-as-fg false
gsettings set org.mate.terminal.profile:/org/mate/terminal/profiles/default/ use-custom-command true
gsettings set org.mate.terminal.profile:/org/mate/terminal/profiles/default/ custom-command 'fish'

echo -e "export HISTCONTROL=ignoreboth:erasedups" >> /home/$USER/.bashrc


gsettings set org.mate.panel.applet.window-list-previews:/org/mate/panel/objects/window-list/prefs/ show-window-thumbnails false

gsettings set org.mate.panel.applet.clock:/org/mate/panel/objects/clock/prefs/ cities "['<location name="" city="Nuremberg" timezone="Europe/Berlin" latitude="49.500000" longitude="11.050000" code="EDDN" current="true"/>']"
gsettings set org.mate.panel.applet.clock:/org/mate/panel/objects/clock/prefs/ format '24-hour'
gsettings set org.mate.panel.applet.clock:/org/mate/panel/objects/clock/prefs/ speed-unit 'km/h'

gsettings set org.mate.panel.applet.workspace-switcher:/org/mate/panel/objects/object-1/prefs/ num-rows 2

gsettings set org.mate.Marco.global-keybindings run-command-terminal "<Primary><Alt>t"
gsettings set org.mate.control-center.keybinding:/org/mate/desktop/keybindings/custom0/ name 'Passwordsafe'
gsettings set org.mate.control-center.keybinding:/org/mate/desktop/keybindings/custom0/ action 'gnome-passwordsafe'
gsettings set org.mate.control-center.keybinding:/org/mate/desktop/keybindings/custom0/ binding '<Primary><Alt>s'

mate-layouts --volumecontrol volctl
gsettings set apps.volctl:/apps/volctl/ osd-enabled false

#Remove the .desktop entry in HOME user folder

rm $HOME/.config/autostart/$app.desktop

